// Package channeltypes renders Nimbu channel schemas as TypeScript types that
// plug into the nimbu-js-sdk typings.
//
// Every channel becomes an object type alias whose members use the SDK helper
// types (ReferenceTo, Select, NimbuFile, ...). Type aliases are used instead of
// interfaces on purpose: the SDK constrains attribute maps with ChannelConfig,
// which has a string index signature, and only type aliases get an implicit
// index signature. A plain interface would fail `NimbuObject<T>` with TS2344.
package channeltypes

import (
	"fmt"
	"sort"
	"strings"
	"unicode"

	"github.com/nimbu/cli/internal/api"
)

const (
	// SDKModule is the module the helper types are imported from.
	SDKModule = "nimbu-js-sdk"
	// CloudModule is the opt-in cloud code typings entry that owns NimbuChannels.
	CloudModule = "nimbu-js-sdk/cloud"
)

// SDK helper type names. They must match the type exports of nimbu-js-sdk.
const (
	tsReferenceTo   = "ReferenceTo"
	tsReferenceMany = "ReferenceMany"
	tsSelect        = "Select"
	tsMultiSelect   = "MultiSelect"
	tsDateTime      = "DateTime"
	tsISODate       = "ISODate"
	tsJSONField     = "JSONField"
	tsNimbuFile     = "NimbuFile"
	tsNimbuGallery  = "NimbuGallery"
	tsNimbuCustomer = "NimbuCustomer"
)

// maxImportLine is the width above which the helper import wraps one name per line.
const maxImportLine = 100

// nativeReferences are the reference targets the API reports for native Nimbu
// types instead of a channel slug. Channel slugs are not reserved, so a channel
// can share one of these names; such references stay untyped.
var nativeReferences = map[string]bool{
	"customers": true, "products": true, "orders": true, "pages": true, "articles": true,
}

// ModuleOptions configures Module.
type ModuleOptions struct {
	// Site is echoed in the header comment.
	Site string
	// StrictChannels marks the module as covering every channel of the site,
	// so nimbu-js-sdk/cloud rejects channel slugs that are not in it.
	StrictChannels bool
}

// Interface renders one channel as a standalone snippet: the helper import
// followed by the exported type. References to other channels fall back to
// the untyped SDK helpers because their types are not part of the snippet;
// self references stay typed.
func Interface(detail api.ChannelDetail) string {
	r := newRenderer([]api.ChannelDetail{detail})
	body := r.renderType(detail)

	var b strings.Builder
	r.writeImports(&b)
	b.WriteString("\n")
	b.WriteString(body)
	return strings.TrimRight(b.String(), "\n")
}

// Module renders one TypeScript module for all given channels. It exports a
// type per channel and augments NimbuChannels in nimbu-js-sdk/cloud so cloud
// code callbacks resolve entries by channel slug. Channels are ordered by slug
// so the output is deterministic.
func Module(channels []api.ChannelDetail, opts ModuleOptions) string {
	sorted := sortedChannels(channels)
	r := newRenderer(sorted)

	bodies := make([]string, 0, len(sorted))
	for _, channel := range sorted {
		bodies = append(bodies, r.renderType(channel))
	}

	var b strings.Builder
	b.WriteString("// Nimbu channel types")
	if site := singleLine(opts.Site); site != "" {
		fmt.Fprintf(&b, " for site %q", site)
	}
	b.WriteString(".\n")
	b.WriteString("// Generated by the nimbu CLI (`nimbu channels types`). Do not edit.\n")
	if r.imports[tsSelect] || r.imports[tsMultiSelect] {
		b.WriteString("// Select options are listed by their name in the API's locale; entries read\n")
		b.WriteString("// in another locale of a multilingual site can carry translated names.\n")
	}
	b.WriteString("\n")
	r.writeImports(&b)
	for _, body := range bodies {
		b.WriteString("\n")
		b.WriteString(body)
	}

	// The augmentation refers to local aliases, never to the exported names:
	// inside `declare module` TypeScript looks names up in the augmented
	// module's exports first, so `Site` there would be the cloud typings' Site.
	b.WriteString("\n")
	for _, channel := range sorted {
		name := r.names[channel.Slug]
		fmt.Fprintf(&b, "type %s = %s\n", aliasName(name), name)
	}
	b.WriteString("\n")
	fmt.Fprintf(&b, "declare module '%s' {\n", CloudModule)
	b.WriteString("  interface NimbuChannels {\n")
	for _, channel := range sorted {
		fmt.Fprintf(&b, "    %s: %s\n", quoteString(channel.Slug), aliasName(r.names[channel.Slug]))
	}
	b.WriteString("  }\n")
	if opts.StrictChannels {
		b.WriteString("  interface NimbuCloudOptions {\n")
		b.WriteString("    strictChannels: true\n")
		b.WriteString("  }\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// TypeName returns the exported TypeScript type name for a channel slug when
// it is rendered on its own.
func TypeName(slug string) string {
	return assignTypeNames([]string{slug})[slug]
}

type renderer struct {
	// names maps the slug of every channel rendered in this output to its type
	// name. References to slugs outside this map use untyped helpers.
	names   map[string]string
	imports map[string]bool
}

func newRenderer(channels []api.ChannelDetail) *renderer {
	slugs := make([]string, 0, len(channels))
	for _, channel := range channels {
		slugs = append(slugs, channel.Slug)
	}
	return &renderer{names: assignTypeNames(slugs), imports: map[string]bool{}}
}

func (r *renderer) renderType(detail api.ChannelDetail) string {
	var b strings.Builder
	doc := []string{singleLine(detail.Name)}
	if doc[0] == "" {
		doc[0] = "Channel"
	}
	doc[0] += fmt.Sprintf(" (channel `%s`)", singleLine(detail.Slug))
	if description := strings.TrimSpace(detail.Description); description != "" {
		doc = append(doc, "", description)
	}
	writeDoc(&b, "", doc)

	var members strings.Builder
	for _, field := range detail.Customizations {
		name := strings.TrimSpace(field.Name)
		if name == "" {
			continue
		}
		writeDoc(&members, "  ", r.fieldDoc(field))
		fmt.Fprintf(&members, "  %s%s: %s\n", propertyKey(name), optionalSuffix(isRequired(field)), r.memberType(field))
	}
	if members.Len() == 0 {
		fmt.Fprintf(&b, "export type %s = {}\n", r.names[detail.Slug])
		return b.String()
	}
	fmt.Fprintf(&b, "export type %s = {\n%s}\n", r.names[detail.Slug], members.String())
	return b.String()
}

// memberType is fieldType plus `| null` for fields that may be blank: the API
// nullifies blank values (keeping the key), so an optional field reads as null,
// not only as undefined. Booleans are always serialized as true or false.
// Required fields stay non-null: required means present after validation.
func (r *renderer) memberType(field api.CustomField) string {
	typ := r.fieldType(field)
	if isRequired(field) || field.Type == "boolean" || typ == "any" {
		return typ
	}
	return typ + " | null"
}

// isRequired reports whether a field is always required. A required field with
// a required_expression is only required when the expression holds.
func isRequired(field api.CustomField) bool {
	return field.Required && strings.TrimSpace(field.RequiredExpression) == ""
}

// fieldType maps a custom field to the TypeScript type of the value that
// `entry.get(field)` returns in the v2 SDK.
func (r *renderer) fieldType(field api.CustomField) string {
	switch field.Type {
	case "string", "text", "email":
		return "string"
	case "integer", "float":
		return "number"
	case "boolean":
		return "boolean"
	case "calculated":
		switch field.CalculationType {
		case "integer", "float":
			return "number"
		case "string":
			return "string"
		default:
			return "string | number"
		}
	case "date":
		// Serialized as YYYY-MM-DD, which the SDK leaves as a string.
		return r.use(tsISODate)
	case "date_time":
		// Serialized as a UTC ISO timestamp, which the SDK decodes to a Date.
		return r.use(tsDateTime)
	case "time":
		// Serialized as an ISO timestamp in the site's time zone: the SDK
		// decodes it to a Date only when that zone is UTC.
		return r.use(tsDateTime) + " | " + r.use(tsISODate)
	case "select":
		options := optionNames(field)
		if len(options) == 0 {
			return "string"
		}
		return fmt.Sprintf("%s<%s>", r.use(tsSelect), strings.Join(options, " | "))
	case "multi_select":
		options := optionNames(field)
		if len(options) == 0 {
			return "string[]"
		}
		return fmt.Sprintf("%s<%s>", r.use(tsMultiSelect), strings.Join(options, " | "))
	case "belongs_to":
		return r.reference(tsReferenceTo, field.Reference)
	case "belongs_to_many":
		return r.reference(tsReferenceMany, field.Reference)
	case "customer":
		// The API embeds the customer as plain JSON (no __type, so the SDK
		// does not build a Nimbu.Customer), or sends only its id when the
		// embed is not allowed.
		return r.use(tsJSONField) + " | string"
	case "file":
		return r.use(tsNimbuFile)
	case "gallery":
		return r.use(tsNimbuGallery)
	case "json", "geo":
		return r.use(tsJSONField)
	default:
		// Unknown to this CLI version; any keeps the type assignable to ChannelConfig.
		return "any"
	}
}

func (r *renderer) reference(helper, target string) string {
	target = strings.TrimSpace(target)
	if nativeReferences[target] {
		if _, isChannel := r.names[target]; !isChannel && target == "customers" && helper == tsReferenceTo {
			// The SDK decodes a `customers` reference to a Nimbu.Customer.
			return r.use(tsNimbuCustomer)
		}
		// Other native targets decode to a plain Nimbu.Object; a channel with
		// the same slug makes the target ambiguous.
		return r.use(helper)
	}
	r.use(helper)
	if name, ok := r.names[target]; ok {
		return fmt.Sprintf("%s<%s>", helper, name)
	}
	return helper
}

// ambiguousReference reports a reference whose target names both a native
// Nimbu type and a channel of this output.
func (r *renderer) ambiguousReference(field api.CustomField) bool {
	if field.Type != "belongs_to" && field.Type != "belongs_to_many" {
		return false
	}
	target := strings.TrimSpace(field.Reference)
	_, isChannel := r.names[target]
	return nativeReferences[target] && isChannel
}

func (r *renderer) use(name string) string {
	r.imports[name] = true
	return name
}

func (r *renderer) writeImports(b *strings.Builder) {
	if len(r.imports) == 0 {
		// Keep the file a module so `declare module` augments instead of
		// declaring an ambient module.
		b.WriteString("export {}\n")
		return
	}
	names := make([]string, 0, len(r.imports))
	for name := range r.imports {
		names = append(names, name)
	}
	sort.Strings(names)
	line := fmt.Sprintf("import type { %s } from '%s'\n", strings.Join(names, ", "), SDKModule)
	if len(line) <= maxImportLine {
		b.WriteString(line)
		return
	}
	b.WriteString("import type {\n")
	for _, name := range names {
		fmt.Fprintf(b, "  %s,\n", name)
	}
	fmt.Fprintf(b, "} from '%s'\n", SDKModule)
}

// sortedChannels orders channels by slug and keeps the first of any duplicates.
func sortedChannels(channels []api.ChannelDetail) []api.ChannelDetail {
	seen := make(map[string]bool, len(channels))
	sorted := make([]api.ChannelDetail, 0, len(channels))
	for _, channel := range channels {
		if seen[channel.Slug] {
			continue
		}
		seen[channel.Slug] = true
		sorted = append(sorted, channel)
	}
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })
	return sorted
}

func optionNames(field api.CustomField) []string {
	seen := map[string]bool{}
	names := make([]string, 0, len(field.SelectOptions))
	for _, option := range field.SelectOptions {
		name := option.Name
		if strings.TrimSpace(name) == "" || seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, quoteString(name))
	}
	return names
}

func (r *renderer) fieldDoc(field api.CustomField) []string {
	var doc []string
	add := func(lines ...string) {
		if len(doc) > 0 {
			doc = append(doc, "")
		}
		doc = append(doc, lines...)
	}
	label := singleLine(field.Label)
	if label != "" && !strings.EqualFold(humanize(label), humanize(field.Name)) {
		add(label)
	}
	if hint := strings.TrimSpace(field.Hint); hint != "" {
		add(hint)
	}
	if expression := singleLine(field.RequiredExpression); field.Required && expression != "" {
		add(fmt.Sprintf("Required when `%s`.", expression))
	}
	if r.ambiguousReference(field) {
		add(fmt.Sprintf("Untyped: `%s` is both a channel and a native Nimbu type.", singleLine(field.Reference)))
	}
	return doc
}

// humanize folds separators so a label like "Publish on" matches publish_on.
func humanize(value string) string {
	return singleLine(strings.NewReplacer("_", " ", "-", " ").Replace(value))
}

func writeDoc(b *strings.Builder, indent string, lines []string) {
	var expanded []string
	for _, line := range lines {
		for _, part := range strings.Split(strings.ReplaceAll(line, "\r\n", "\n"), "\n") {
			expanded = append(expanded, strings.TrimRight(strings.ReplaceAll(part, "*/", "*\\/"), " \t"))
		}
	}
	if len(expanded) == 0 {
		return
	}
	if len(expanded) == 1 {
		fmt.Fprintf(b, "%s/** %s */\n", indent, expanded[0])
		return
	}
	fmt.Fprintf(b, "%s/**\n", indent)
	for _, line := range expanded {
		if line == "" {
			fmt.Fprintf(b, "%s *\n", indent)
			continue
		}
		fmt.Fprintf(b, "%s * %s\n", indent, line)
	}
	fmt.Fprintf(b, "%s */\n", indent)
}

func propertyKey(name string) string {
	if isIdentifier(name) {
		return name
	}
	return quoteString(name)
}

func isIdentifier(name string) bool {
	for i, r := range name {
		switch {
		case r == '_' || r == '$' || unicode.IsLetter(r):
		case i > 0 && unicode.IsDigit(r):
		default:
			return false
		}
	}
	return name != ""
}

// quoteString renders a single-quoted TypeScript string literal.
func quoteString(value string) string {
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range value {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '\'':
			b.WriteString(`\'`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\u2028':
			b.WriteString(`\u2028`)
		case '\u2029':
			b.WriteString(`\u2029`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, `\u%04x`, r)
				continue
			}
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

func singleLine(value string) string {
	return strings.Join(strings.Fields(value), " ")
}

func optionalSuffix(required bool) string {
	if required {
		return ""
	}
	return "?"
}
