// Nimbu channel types for site "demo".
// Generated by the nimbu CLI (`nimbu channels types`). Do not edit.
// Select options are listed by their name in the API's locale; entries read
// in another locale of a multilingual site can carry translated names.

import type {
  DateTime,
  ISODate,
  JSONField,
  MultiSelect,
  NimbuCustomer,
  NimbuFile,
  NimbuGallery,
  ReferenceMany,
  ReferenceTo,
  Select,
} from 'nimbu-js-sdk'

/** 2020 archive (channel `2020-archive`) */
export type Channel2020Archive = {
  note?: string | null
}

/** Authors (channel `authors`) */
export type Authors = {
  name: string
  posts?: ReferenceMany<BlogPosts> | null
}

/**
 * Blog posts (channel `blog-posts`)
 *
 * Articles shown on the blog.
 * One entry per post.
 */
export type BlogPosts = {
  title: string
  body?: string | null
  /** Contact e-mail */
  contact?: string | null
  published?: boolean
  views?: number | null
  rating?: number | null
  publish_on?: ISODate | null
  published_at?: DateTime | null
  /**
   * Local time of day.
   * Shown on the event card.
   */
  starts_at?: DateTime | ISODate | null
  status: Select<'draft' | 'published' | 'it\'s live'>
  tags?: MultiSelect<'news' | 'a\\b'> | null
  mood?: string | null
  labels?: string[] | null
  author: ReferenceTo<Authors>
  /** Related posts */
  related?: ReferenceMany<BlogPosts> | null
  legacy?: ReferenceTo | null
  owner?: JSONField | string | null
  reviewer?: NimbuCustomer | null
  /** Required when `published == true`. */
  venue?: string | null
  /** Cover *\/ image */
  cover?: NimbuFile | null
  photos?: NimbuGallery | null
  metadata?: JSONField | null
  location?: JSONField | null
  word_count?: number | null
  summary?: string | null
  score?: string | number | null
  future?: any
}

/** Blog posts (legacy) (channel `blog_posts`) */
export type Blog_Posts = {
  title?: string | null
}

/** Select (channel `select`) */
export type SelectChannel = {}

/** Site settings (channel `site`) */
export type Site = {
  tagline: string
}

type __NimbuChannel_Channel2020Archive = Channel2020Archive
type __NimbuChannel_Authors = Authors
type __NimbuChannel_BlogPosts = BlogPosts
type __NimbuChannel_Blog_Posts = Blog_Posts
type __NimbuChannel_SelectChannel = SelectChannel
type __NimbuChannel_Site = Site

declare module 'nimbu-js-sdk/cloud' {
  interface NimbuChannels {
    '2020-archive': __NimbuChannel_Channel2020Archive
    'authors': __NimbuChannel_Authors
    'blog-posts': __NimbuChannel_BlogPosts
    'blog_posts': __NimbuChannel_Blog_Posts
    'select': __NimbuChannel_SelectChannel
    'site': __NimbuChannel_Site
  }
  interface NimbuCloudOptions {
    strictChannels: true
  }
}
